# Generated by Django 3.0 on 2021-12-30 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('contact', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='JobCard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jobcard_number', models.CharField(max_length=255, unique=True)),
                ('timestamp', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('total_amount', models.FloatField()),
                ('advance', models.FloatField(blank=True, null=True)),
                ('due', models.FloatField(blank=True, null=True)),
                ('cheque_no', models.CharField(blank=True, max_length=255, null=True)),
                ('delivery_date', models.DateTimeField()),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('details', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, upload_to='product_image')),
                ('unit_price', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_quantity', models.IntegerField()),
                ('quantity', models.IntegerField()),
                ('product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='crm_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Quatation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quatation_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('total_discount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('validity', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('jobcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.JobCard')),
            ],
        ),
        migrations.CreateModel(
            name='JobCardItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_price', models.FloatField(blank=True, null=True)),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('amount', models.FloatField(blank=True, null=True)),
                ('prev_quantity', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(blank=True, null=True)),
                ('jobcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crm_app.JobCard')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='crm_app.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('date', models.DateTimeField()),
                ('delivery_date', models.DateTimeField()),
                ('done', models.BooleanField(default=False)),
                ('total_discount', models.FloatField(blank=True, null=True)),
                ('total_amount', models.FloatField(blank=True, null=True)),
                ('tax', models.FloatField(blank=True, null=True)),
                ('total_due', models.FloatField(blank=True, null=True)),
                ('note', models.TextField(blank=True, max_length=2048, null=True)),
                ('jobcard', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='crm_app.JobCard')),
            ],
        ),
    ]
