# Generated by Django 3.0 on 2021-12-30 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0002_jobcarditems_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcarditems',
            name='product',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
