# Generated by Django 3.0 on 2021-12-30 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0003_auto_20211230_0035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobcarditems',
            name='prev_quantity',
        ),
        migrations.AddField(
            model_name='jobcarditems',
            name='details',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
