# Generated by Django 3.0 on 2021-12-31 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0004_auto_20211230_0102'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobcard',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='quotation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobcard',
            name='quotation_number',
            field=models.CharField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='jobcard',
            name='jobcard_number',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
