# Generated by Django 3.0 on 2022-01-02 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm_app', '0005_auto_20211230_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobcard',
            name='delivery_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
