// SKELETON
export const SKELETONLOADING = "SKELETONLOADING";

// AUTH
export const LOADING = "LOADING";
export const USER_LOADING = "USER_LOADING";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
export const PASSWORD_VALIDATION = "PASSWORD_VALIDATION";
export const WRONG_CREDENTIALS = "WRONG_CREDENTIALS";
export const TOGGLE_CHECKING_CREDENTIALS = "TOGGLE_CHECKING_CREDENTIALS";

// Groups
export const ALL_PERMISSIONS = "ALL_PERMISSIONS";
export const ALL_GROUPS = "ALL_GROUPS";
export const MANAGE_GROUPS = "MANAGE_GROUPS";
// ALL USERS
export const ALL_USERS = "ALL_USERS";
export const ALL_USERS_LIST = "ALL_USERS_LIST";
export const INIT_USER_ACTION = "INIT_USER_ACTION";
export const SUCCESS_USER_ACTION = "SUCCESS_USER_ACTION";
export const ERROR_USER_ACTION = "ERROR_USER_ACTION";

// PAGE TRANSITION
export const PAGE_LOAD = "PAGE_LOAD";
export const PAGE_LOADED = "PAGE_LOADED";
export const SPLASH_LOAD = "SPLASH_LOAD";

// ALERT
export const ALERT_MESSAGE = "ALERT_MESSAGE";

// Uload File Progress
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";

// CRM
export const PRODUCTS_DATA = "PRODUCTS_DATA"
export const PRODUCT_DETAILS = "PRODUCT_DETAILS"

export const CUSTOMERS_DATA = "CUSTOMERS_DATA"
export const CUSTOMERS_DETAILS = "CUSTOMERS_DETAILS"
export const CUSTOMERS_JOBCARDS = "CUSTOMECUSTOMERS_JOBCARDSRS_DETAILS"

export const SEARCH_CUSTOMER = "SEARCH_CUSTOMER"
export const SEARCH_PRODUCT = "SEARCH_PRODUCT"
export const JOBCARD_DATA = "JOBCARD_DATA"
export const JOBCARD_NUMBER="JOBCARD_NUMBER"
export const JOBCARD_DETAILS="JOBCARD_DETAILS"

// SEARCH
export const SEARCHING = "SEARCHING";
export const SEARCH_DONE = "SEARCH_DONE";

//DROPDOWN OPTIONS

// PASSWORD RESET
export const REQUESTING_PASSWORD_RESET = "REQUESTING_PASSWORD_RESET";
export const SUCCESS_PASSWORD_REQUEST = "SUCCESS_PASSWORD_REQUEST";
export const FAILURE_PASSWORD_REQUEST = "FAILURE_PASSWORD_REQUEST";
export const VALIDATING_RESET_TOKEN = "VALIDATING_RESET_TOKEN";
export const SUCCESS_TOKEN_VALIDATION = "SUCCESS_TOKEN_VALIDATION";
export const FAILED_TOKEN_VALIDATION = "FAILED_TOKEN_VALIDATION";


